{% set python_min = '3.11' %}
{% set name = "subgroups" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/subgroups-{{ version }}.tar.gz
  sha256: 6ce36e7c9e2a7a91349e86a648481f36ddf95a8d24523102cd4c3244abd0be47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=2.1.4
    - bitarray >=3.0.0
    - statsmodels >=0.14.0

test:
  imports:
    - subgroups
    - subgroups.tests
  commands:
    - pip check
    - python -c "import subgroups.tests as st; st.run_all_tests()"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/antoniolopezmc/subgroups
  summary: subgroups is a python library which contains a collection of subgroup discovery algorithms and other data analysis utilities.
  license: BSD-4-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - antoniolopezmc
